version: "3"

services:
  api-server:
    build:
      context: .
    container_name: api-server
    image: api-server
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - MONGO_URL=mongodb://host.docker.internal:27017/parts
    volumes:
      - ./logs:/logs
    networks:
      - app-network
    ports:
      - "${PUBLIC_PORT}:${PORT}"

networks:
  app-network:
    driver: bridge
